version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: dify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

  web:
    image: langgenius/dify-web:latest
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    image: langgenius/dify-api:latest
    ports:
      - "5001:5001"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  mcp-server:
    image: ghcr.io/langgenius/mcp-server:latest
    ports:
      - "9001:9001"
    environment:
      - APP_ID=teste
      - API_KEY=testando
    depends_on:
      - web

volumes:
  pgdata:
